/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-southeast-1",
  aws_cognito_identity_pool_id:
    "ap-southeast-1:93bb468b-c613-427d-bde3-79bb825d72ea",
  aws_cognito_region: "ap-southeast-1",
  aws_user_pools_id: "ap-southeast-1_VLDb8g2QD",
  aws_user_pools_web_client_id: "6spntf21d61pna3sn61koes496",
  oauth: {
    domain: "mtx944338ab-944338ab-dev.auth.ap-southeast-1.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: "https://dev8582.d3i1w8nk6i91rh.amplifyapp.com/",
    redirectSignOut: "https://dev8582.d3i1w8nk6i91rh.amplifyapp.com/",
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
};

export default awsmobile;
