/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:deed8c74-c663-40a2-96bf-85de3457f5e5",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_OecljbELS",
    "aws_user_pools_web_client_id": "7jm3e1jv20lndmp4cm3emdajki",
    "oauth": {
        "domain": "mtx-dev.auth.ap-southeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://master.dxo03xahtgqrz.amplifyapp.com/",
        "redirectSignOut": "https://master.dxo03xahtgqrz.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
